export * from './models/declamation'
export * from './routes/declamations'
export * from './controllers/useWaveform'
export * from './controllers/useDeclamationsRepository'
export { default as DeclamationsListPage }  from './pages/DeclamationsListPage.vue'
export { default as DeclamationEditForm } from './components/DeclamationEditForm.vue'
export { default as DeclamationsListItem } from './components/DeclamationsListItem.vue'
export { default as DeclamationsList } from './components/DeclamationsList.vue'
export { default as DeclamationPlayer } from './components/DeclamationPlayer.vue'