export * from './models/declamation'
export * from './routes/declamations'
export { default as DeclamationsListPage }  from './pages/DeclamationsListPage.vue'
export { default as DeclamationsCreatePage }  from './pages/DeclamationsCreatePage.vue'
export { default as DeclamationEditForm } from './components/DeclamationEditForm.vue'